### ISSUE TITLE
USA births dataset?

### ISSUE THREAD

**Issue by jakevdp** [mwaskom/seaborn-data#1]
Any interest in adding this dataset to the repo? I just put it together yesterday: https://github.com/jakevdp/data-CDCbirths
It's been analyzed in the past by Andrew Gelman & his team, and I think allows for some interesting possibilities!

**Comment by mwaskom** [comment]
This is a cool dataset, although I'm not sure it shows off any of the things seaborn is particularly good at doing, since most of the plots you'd make with it are single timeseries traces. Unless you had something in particular in mind? I'd love to replace the `tips` dataset with something that is actually somewhat scientifically interesting!

I also think it would be nice to have a more general purpose PyData dataset repository, seaborn-data isn't quite that, but I'd be happy to point `load_dataset` at it (the current system was just a quick hack).

**Comment by jakevdp** [comment]
That's a good idea! Note that there's already something like this in the broader ML community: http://mldata.org/
Scikit-learn has tools to access this data: http://scikit-learn.org/stable/datasets/mldata.html

**Comment by jakevdp** [comment]
I think you're right that this data does not necessarily take advantage of Seaborn's strengths, and in that light it doesn't make much sense to add it here. Closing the issue!
